version: '3.4'
services:
  pip-kit:
    image: itisfoundation/pip-kit:latest
    build:
      context: ./pip-kit
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
    volumes:
      - .:/home/itis/work
  python-with-pandas:
    image: itsfoundation/python-with-pandas:3.6-alpine
    build:
      context: ./python-with-pandas/3.6-alpine
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
  python-with-pandas-py27:
    image: itsfoundation/python-with-pandas-py27:3.6-alpine
    build:
      context: ./python-with-pandas/3.6-alpine/py2.7
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
  devpi:
    image: itisfoundation/devpi:latest
    build:
      context: ./devpi
      labels:
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
    working_dir: /data
    volumes:
      - ./data:/data
    ports:
      - 31411:31411
    environment:
      DEVPISERVER_DEVPI_LDAP_URL: ldaps://ds1.example.com
      DEVPISERVER_DEVPI_USER_TEMPLATE: uid={username},ou=users,dc=example,dc=com
      DEVPISERVER_DEVPI_GROUP_SEARCH_BASE: ou=groups,dc=example,dc=com
      DEVPISERVER_DEVPI_GROUP_FILTER: (&(objectClass=posixGroup)(memberUid={username}))
      DEVPISERVER_DEVPI_GROUP_ATTRIBUTE_NAME: uid
